### ISSUE TITLE
How to compile for Linux ? 

### ISSUE THREAD

**Issue by Tirguy** [Adrianotiger/ESPToolsGUI#4]
Sorry, i'm "newbie" :-(
I've installed cx_Freeze and it looks to work ...
But in order to compile your application under Linux Debian, i try different things but none work :-(

Have you something that explain how to do ? 

Thanks a lot

Thierry

**Comment by Adrianotiger** [comment]
This project use the .net forms. So it works only on windows.
Sorry

**Comment by Tirguy** [comment]
> This project use the .net forms. So it works only on windows. Sorry
it's a pity :-(
